[package]
name = "eidonkey"
version = "0.1.0"
authors = ["david <david.tillemans@cryptable.org>"]

[dependencies]
hyper = "0.8"
mime = "0.2"
getopts = "0.2"
openssl = "0.7"
serde_json = "0.7"
data-encoding = "1.1.2"

[dependencies.donkeycard]
path = "donkeycard"
features = [ "mock_pincode" ]
