[package]
name = "eidonkey"
version = "0.1.0"
authors = ["david <david.tillemans@cryptable.org>"]

# Build pincode
# links = "pincode"
build = "build.rs"

[build-dependencies]
cmake = "0.1"

[dependencies]
hyper = "0.9"
mime = "0.2"
getopts = "0.2"
openssl = "0.7"
serde_json = "0.7"
data-encoding = "1.1.2"
libc = "0.2"

[features]
default = [ "tlsv1_2" ]
#mock_pincode = []
tlsv1_2 = [ "openssl/tlsv1_2" ]