#!/bin/bash -x

# Run as sudo during installation

# Add the application to the Application firewall of Apple 
/usr/libexec/ApplicationFirewall/socketfilterfw --add $HOME/Applications/eidonkey
/usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp $HOME/Applications/eidonkey

chmod u+s post-startup-eidonkey