#!/bin/bash -x

# Run as sudo during installation
# Open personal FW to allow connections to the service
# Add the application to the Application firewall of Apple 
/usr/libexec/ApplicationFirewall/socketfilterfw --add $HOME/Applications/eidonkey
/usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp $HOME/Applications/eidonkey

# Sign the components
shasum -a 256 -t post-install-eidonkey > eidonkey.sig
shasum -b -a 256 -b eidonkey >> eidonkey.sig
shasum -b -a 256 -b pincode >> eidonkey.sig
shasum -b -a 256 -b post-startup-eidonkey >> eidonkey.sig
shasum -b -a 256 -b firefox/certutil >> eidonkey.sig

# Secure access to application directory and applications
chmod 500 eidonkey
chmod 500 eid_pin
chmod 500 firefox/certutil
chmod 500 eidonkey.sig
chmod 500 post-install-eidonkey
chmod 500 post-startup-eidonkey
