#!/bin/bash -x

# Run as sudo during installation
# Open personal FW to allow connections to the service
# Add the application to the Application firewall of Apple 
/usr/libexec/ApplicationFirewall/socketfilterfw --add $HOME/Applications/eidonkey
/usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp $HOME/Applications/eidonkey

# Sign the components
shasum -a 256 -t post-install-eidonkey > eidonkey.sig
shasum -b -a 256 -b eidonkey >> eidonkey.sig
shasum -b -a 256 -b pincode >> eidonkey.sig
shasum -b -a 256 -b post-startup-eidonkey >> eidonkey.sig
shasum -b -a 256 -b firefox/certutil >> eidonkey.sig

# Secure access to application directory and applications
chmod 500 eidonkey
chmod 500 eid_pin
chmod 555 firefox/*
chmod 500 eidonkey.sig
chmod 500 post-install-eidonkey
chmod 500 post-startup-eidonkey
chmod 555 import-ca-firefox

ln -s /opt/eidonkey/import-ca-firefox /usr/bin/import-ca-firefox

# Copy the Launch script to final destinations
cp org.cryptable.eidonkey.plist /Library/LaunchDaemons/
cp org.cryptable.import-ca-firefox.plist /Library/LaunchAgents/
