#!/bin/bash -x

# Chrome/linux browser keychain
openssl asn1parse -in cacert.crt -inform PEM -out cacert.der 2>&1 >/dev/null
# Remove your old CA Certificate
certutil -D -n "My eidonkey CA" -d sql:"${HOME}/.pki/nssdb" 2>&1 >/dev/null
# Add your old CA Certificate
certutil -A -n "My eidonkey CA" -t Cc,, -i ./cacert.crt -d sql:"${HOME}/.pki/nssdb" 2>&1 >/dev/null

# Add to Firefox keystore
# package libnss3-tools has to be installed
for dir in ${HOME}/.mozilla/firefox/*
do
	if [ -d ${dir} ] 2>&1 >/dev/null
	then
		if [ ${dir: -8} == ".default" ] 2>&1 >/dev/null
		then
			# ignore: remove certificate gives error SEC_ERROR_LEGACY_DATABASE, when certificate not found
			certutil -D -n "My eidonkey CA" -d "${dir}" 2>&1 >/dev/null
			certutil -A -n "My eidonkey CA" -t Cc,, -i cacert.crt -d "${dir}" 2>&1 >/dev/null
		fi
	fi
done

# Remove the der version of the old CA Certificate
rm -f cacert.der
rm -f cert.der

